apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-secret
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:DADCm2+xF36EZVNoXZOsSwEgHvW+3X4uGuDBodk=,iv:HRat3F9+CDEaQz4AHg8DXVNq9u/i53g4eOwZ7+2Rvsw=,tag:wLfscW6tJHWYHDwzBwoyqA==,type:str]
  DB_URL: ENC[AES256_GCM,data:byQ5pVtxnzsEGSMk/vrBVlT00i9qcpr1FsPYKpQ+f5nzUdQoRutL68qklPeEHwjKIPjc65bknnE+QV0vpGBefED3A8k6ZmFeuWsS0rBvuRwWjxHl7xhgzWLr/UKQ4pBExz65m04IjSHm0A==,iv:iYu6sh7e/tSyl248hKGHLl4vNkda8xsENv3wM5bBkYI=,tag:TqGtp+AIVUPw1ulMtalAmQ==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWXVZQVlFeVBIY1hKenZw
        bVRmcXpvNVN3SEFBUVk2TExKNUhxaDFqRTFnCnhCSmZ2VHJkcWw5OXBjQmtKV0JV
        NGVkMktZck1pcU1TQ3l0TnhPOFJCNGcKLS0tIC9yZEpjWm13dE1MMW5uZWtiL3NM
        ejJDRzlySG04OG1zSjVlL2NPTG0zMncKNbDFCvJzTZ36IyShcUb1wVayxDubnBRQ
        E44J7hHPoXkT5jElliUTfG/5PDDFu6d7xUqjnIUY4gAD8V46eFYxKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-17T00:15:11Z"
  mac: ENC[AES256_GCM,data:3USoMIuqHSAWu9OAbaEib2eglZpZ/N4/n0L+SqvziYV4ZosG5KkEZXkbxE3e3LLmA0Di4ek6YImKaNSMEgD4QYrB8vzEr8M8OLTGbWqo8nkwnVEp7GUkCbg+yR6z3p1+Cs5SbZZNualYj9KNPzhrIKQARXiik6sAZzzLGdaF2ok=,iv:N2npNNlJl4yIMa9w2Uu0Dhlc4uZgIc3/Ix1SLbIL8tU=,tag:5etImUA4ghR6mhxpvZmC+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
