apiVersion: v1
kind: Secret
metadata:
  name: homarr-secret
stringData:
  SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:EouykkoGNf1kVzxDIXchsUydAQcCvGk0dllho55qIPzHvFzrMmmTfnsbWnx6WxmA6tjoCjgKcpAfzsd1jEMfAg==,iv:LpTPP3bpad5+84jTGc0/LzADAX2+kq4y2BJiK7k3oVc=,tag:aYm0iZC0ReynWT1aCdAE5g==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWXpMU2VSY3F4RFEzUTdY
        VXB5c1Fwd29sdjZMY3h5OENpNVlRU1RGRWtrCmR2TFFPTDZ2UjNYK3JtNjBBSjhv
        LzZoSVBiOGdxeU5wRnB4aXhhMGxMTWcKLS0tIEJqRkd6Mnd2WXo1RzFTZUxSSlRk
        NVJZbm5XME5heU5sRFQzNEVPMnNabm8KSY9NLQ8HXriZgzwIYl9AP/47hfs05bQM
        nlTLZ1ir14GGZQ7TPCGBqgnyTRxxRJcgPw1rEYsw3b4MzaUgKGzJ9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-01T22:55:39Z"
  mac: ENC[AES256_GCM,data:i9pyyp4hbYhRLw2NBHjqCcKmzl32+fqN/YrGTFGHnDs2dwDRgeHqRqYI7J2EW8+aBqhnhyUZO4Z+kavrC/X1NGIRPokHVbbuSoIC7G6ay9x5NnCQ9HR1cqsU70SdeOs7nSjes/mnxSIaiP0t1A71EAy3Wv8rPuGsNHlu1lCWJUI=,iv:Pv9CEFZkL3uCV44Xhz8lPgJXIDXg0L+OowhSeRzBBW0=,tag:6mPwmfchIV3yPShVe4THiA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
