apiVersion: v1
kind: Secret
metadata:
  name: grafana-discord-webhook
stringData:
  discord-webhook-url: ENC[AES256_GCM,data:0EktzItlG+hSM/4IkpvDUorX06M2tbJuiY+GBkNhkDkgcSGrPpP/43clWCVNDcbBa4M2UZ5ENcQq6/pCkj8Eo/Sm9xASnRGY9eol1mKb7pTLYVp/0uAVnpq2DRlTV+6+f6PC88Zn4pLYgFYe7eZj3P3cP1yW0BF3iw==,iv:l7+usxmUTidQ+oHcIO6GlYZga8HIeJGn+p8Qsivccfs=,tag:z3umlqaJbMmjahq18k+47Q==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacmIzZU0zZndiSm9UMHJY
        d3NxQ3N0ejhJTys5YVQyYjROWFRPekZFQlVvClBGKzQzNXQxaFp0TStXak1aUGFZ
        R1E1cExyUHlzejloWjNLMEVucUtKeUEKLS0tIHFTeXFHMDh0YjFLZUtYN2ZKUDdh
        U05vNWZEbE0rTTVyNm12cFY2MUp4NU0KhO2KT0D6RlCmjihHde1oHzte/29iJp6v
        wxqFp5cF6NJnJ5Nyw1h1qKSW2O/0qseXHmsLYe8lpwyy4nsXie8JjQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T02:39:05Z"
  mac: ENC[AES256_GCM,data:qaWZWhRdbN0XR24JjnFCRoey308jDfEpIDNKibXGFuZIsl42y3ZKMIzqx0sYbmQaJZIACUqEaFRc/UZAIOnR7SknkQ5poC9LvayAz8OY4gRUQxaCVruEIzlojB/4F2VV74aaG1ex9rd8wrueALYGwD7pAYIR74ntMBh3l51Vmvw=,iv:XnzkBeCCcWmDoWhdatl+xc9NQWnVsBcGusSiWOIhDfk=,tag:+BRgtu8bVStgmvqcE/jzPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
