---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  interval: 1h
  values:
    crds:
      enabled: true
    prometheus:
      prometheusSpec:
        replicas: 1
        retention: 14d
        retentionSize: 10GB
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 20Gi
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 4Gi
    alertmanager:
      alertmanagerSpec:
        replicas: 1
        storage:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 1Gi
    grafana:
      sidecar:
        dashboards:
          enabled: true
          searchNamespace: ALL
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: default
              orgId: 1
              folder: ""
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          trivy-operator:
            gnetId: 17813
            revision: 2
            datasource: Prometheus
      persistence:
        enabled: true
        size: 2Gi
      admin:
        existingSecret: kube-prometheus-stack-grafana-secret
        passwordKey: admin-password
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki.monitoring.svc.cluster.local:3100
          access: proxy
          isDefault: false
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true
