apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-grafana-secret
stringData:
  admin-user: ENC[AES256_GCM,data:3cvT4MI=,iv:z5cJQwJsbqHwW05lEKiRYIDKAix5B/aO8+0wtchIJw0=,tag:NFWwANtQUwSgxdNnhQDLBg==,type:str]
  admin-password: ENC[AES256_GCM,data:MtvAT8vQpZ0byb6bI0kWNDswfO5I9dxIVFZJdhmMzA==,iv:OeeBmlJckpbTkDrr3cgJ5z/jrLL0iXz1WbYXSgVG9pM=,tag:K/kcUvU36c27TwEt4VdQCg==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RTl6VGpRdFJzNDd5bVZp
        VDJzbXBURlFUZWU2VXZUandTK0VINDJXRHdzCkVVN0dkSzEzQlEzaGRCUXZKU003
        M3dVZDFVVmFyckliTlVLY3prUGd2NFkKLS0tIHRnMkZtbDR2M3BubHpNQi9xUWpi
        SXNnSHFHRnNKeDJXVnhmUFZWUWlCdmMKQ5TYHtJCZ4l4962aY4bydfciukmhwSks
        KlmyjZed7XnuhvXXHC/ybTSErpx5LvdWVHPYFpdJwcQNL+H9DNK2VQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T00:14:36Z"
  mac: ENC[AES256_GCM,data:BXVx3hxEIoy3OxAH2U97vwp8uII48KsYEkkanQCj+Q357G0cTXOlQKzceA6H3ifo4+hUG6wXBiG1KYAG8+C0ozrJMskMU/dQ6DmiCXGLNW4ax5EIsBj1Ul3hoZRVirY8SKoFdJuw6gpLWSvqdFEOYpQuuu5Mti5L1JUKhzWRqTo=,iv:UcgQTZ8WMOhimINx8wPGVabboWSiZPiOKkU2wtcaPoY=,tag:h6JIfEEA+dPt8Q1Bsd1Jyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
