apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-grafana-secret
stringData:
  admin-password: ENC[AES256_GCM,data:E1cHdsQrXoCylK7Yv7/DsDZte+B70kQ0UjQgK2ywIw==,iv:yBkrv4GNuaA8XYG4CqFvDpG1hM22PyCN89f/mzAVXg8=,tag:ARW8zCu3FVpzEke3U0Wk2w==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWWFzL25CVlFOcG8wdXc5
        eVpCM3VnS3Y4Wm9QSTkrMkRIWEFUdUNTNmlBCjlSL1VaK29vSGhLbFBIbkY4T05N
        WDBsN3FTN1Z6VkE5SDJjbjBaSXVteFkKLS0tIHU5YlpHdkdBUk92aEU5ZnVNRkZh
        bWdHYzZ6QzhRUTRIdXZQVFFidmp5YW8KKLFbHoI+Padx6ggHixMkndTz/kBVsjK6
        72WfhEQiRmwn1EP336AybyblLnwEq1fl8iNj8h9fXIvtk/oeHJeESQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-01T23:00:10Z"
  mac: ENC[AES256_GCM,data:cFKFe1xAYUqO/Q8RiBTrRgex1u0VQS8vvPldSmKYIfOH5ZQYFRza5yV86ZN4NgvVxuwzYQQJ6/6tKJq5BmgKVuTxOvSlxGCsVDzC49myDUEQ1nIMvynPGIYyDdktlZzAnSfcWiEJf2p9dEo+4Oo4cEDvcyT471w3ynCnLAaPRr8=,iv:4vcJ5rfJ2UdD5O06NI3fBKR3Bez03sZCk0nTyWoEB9Y=,tag:4+Y9RemEjm52spHHpOa2TA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
