apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-grafana-secret
stringData:
  admin-user: ENC[AES256_GCM,data:PvK5uhDEFVp6gvk=,iv:7k0h1HucV70XObGbz6GfNrBjlB9528bGsZixSEU7Veo=,tag:QcprmFQm5df5g5N+rjuQGg==,type:str]
  admin-password: ENC[AES256_GCM,data:ZZykXgyDpbc94l8fkegXItxzRwzOxk/gPlsUWWY3MA==,iv:NEO2SpjMnnvtWXu+wtb0i17QOQK19JT2Sc3ydHpIg4A=,tag:zEDz8/Xd9gHbiA8NqzlKVA==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbENwVW0wcVZNVlpRWGJE
        V3VlbjBtSkVpMmFDNGorWGVDRVBzNDQwY2lFCkdYTG82Y2J6SzJGZTBnTFhhNjJn
        ckFQa2RyRlpzR29ybFJLTVZNdnZnYzAKLS0tIFFuM0NJVVRZVHFGQmdsTXh3VDJo
        YUNaanVQVElvWStYcysvL1hXWTN2d1UKm8N3sbJ1ycVI6dT3OQBQ/LNQi/eUtFW/
        NuAlHeeNIkvoRVpz1R0KTK/zGTVYAJK5Afh2Yxh3346rhQsMC6ysQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T02:45:32Z"
  mac: ENC[AES256_GCM,data:U/UN3cMLiJ3js1yYzzSy3CTB3W3QlLdI08CEiNeWVLjSoOTMnY7hjJeobr/xA2/lg2tgDREGjJzReDKAtNBHEyzPPowUM1aSiBW/SjtLwR1uYBxt0Cp/bxZ0Bg608AaNPyo6XqRbeYBjam+MS2GeqySRVVQdnKUgq8RELBTMcKc=,iv:AKcmYBcaifR8rrzl26ym1odUSRE5Hm+7eshjTMEvWMA=,tag:lXfSBVdN7XfKS+dgj8Hp9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
