apiVersion: v1
kind: Secret
metadata:
  name: gatus-discord-webhook
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:8g8ui3ULGumRwzC91D7on9gcBcuu0kzZf5cJFkSOouI+2orFTYIpjr73BMB4P3lUZcLTMFxoFMdxOZzH6RNzIoeViKQOl7Lo3NFcinK6LX+C7qjMIX2bDBN5X6NtnX49VJce6CmyI3WJcxCb9yEg6hvKSmwVtLV6RA==,iv:ogVgGigGLrCygf9JFmKr7pqfZXqJDf65EWaKWIJFNME=,tag:Ry98hTe76MrPGC7I7KDtpA==,type:str]
sops:
  age:
    - recipient: age1dq2tahm820v40c0d55p0x84hlt9tlunh5lq32gr9lszkwelpv4mqv2wc0v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQc2hmZnR3MHBmVmxXWTU1
        V0lUMnRIMHRVSlc1Rk5DRjZCZ2dSb1FJR3o0CmZBNDI1dWtPOUFVeWdOdUtWa3ZJ
        NUpJaVB6eHJYV1lmUzZVQS9TNkFqZVkKLS0tIFl6VE5nV0VUV1RZemxGZVVzajJG
        Y3V0MUFrNFFqTEo1QXRvR1lWWDdXRFkK1BKllYoY8fNOC/RXyO3yutM/sKdq9jkE
        k0wXL8iNxYvwgjqN9c1Wy9Hrbb4XT7rqBPLrJc1vUFmRP8uRKVh6VQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T18:37:31Z"
  mac: ENC[AES256_GCM,data:3HD5Vl8tl38pczXzyKJtUKIpyEIDmk6IYoyt0mC+Ad66Dv3DFb0B0TZAunSl97CRuk1ejXWaVYFnIzw0oFkHlpDwdMU/p/Faa1gMv68F5zLa5dqeqU0Ez8EL0QqQ3zpvMKzX5013Z7Eo5vrxxS76qUJJQ7iNG30JZisQez38enM=,iv:gu6T4kaMRHWTEATHGR9jdLndqyHsvWyy57sQWrGnYd4=,tag:zuLWZ3apKo3plEYh/Z/A8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
